[package]
name = "call_in_order"
version = "0.1.0"
authors = ["Ryan Collingham <ryan@tokencard.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
